### ISSUE TITLE
Rubocop extension

### ISSUE THREAD

**Issue by tejasbubane** [toptal/active-job-style-guide#6]
Thanks for this styleguide. I learnt a few good practices and sidekiq's features. 

Does rubocop extension corresponding this style-guide already exist somewhere? I could not find any mentioned in this guide, nor in the [rubocop docs](https://docs.rubocop.org/rubocop/extensions.html#cop-extensions).

I am planning to create such extension. Not all rules can be checked by rubocop, but some sure can and that would be helpful. 
I thought of checking with maintainers here before creating the new extension to avoid duplicate work.

**Comment by pirj** [comment]
There were a few internal cops as far as I remember.
1. [Models as arguments](https://github.com/toptal/active-job-style-guide#active-record-models-as-arguments). As I recall, it was prone to false positives. E.g. `stripe_id` is not an id of a `Stripe` model.
2. [Queue assignments](https://github.com/toptal/active-job-style-guide#queue-assignments). Quite useful.

@bbatsov Are there any plans to make those cops available to the public?

> I am planning to create such extension

Fantastic!

There's also [this bag of notes](https://github.com/toptal/active-job-style-guide/issues/1) if you're up to extend the guide itself.

On a side note, I don't have enough capacity to continue building and contributing to this guide myself, but I'll be happy to maintain it under @rubocop organization.

**Comment by pirj** [comment]
An extension exists it turns out https://github.com/dvandersluis/rubocop-sidekiq/ thanks to @dvandersluis
I'll close this as completed.
